name: Test

on:
  push:
    branches: ["qa"]
  pull_request:
    branches: ["qa"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
